# Generated by Django 5.2.7 on 2026-01-02 10:39

import app.utils.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(50)])),
                ('email', models.CharField(validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(50)])),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'person',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.person')),
                ('birthday', models.DateField(validators=[app.utils.validators.Validators.validate_birthday])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(1)])),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999999999.99)])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='person/natural_person', validators=[app.utils.validators.Validators.validate_picture])),
            ],
            options={
                'verbose_name': 'NaturalPerson',
                'verbose_name_plural': 'NaturalPersons',
                'db_table': 'natural_person',
                'managed': True,
            },
            bases=('app.person',),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('email',), name='unq_person_email', violation_error_message='E-mail is already registered.'),
        ),
        migrations.AddConstraint(
            model_name='naturalperson',
            constraint=models.CheckConstraint(condition=models.Q(('gender__in', ['M', 'F', 'O'])), name='chk_naturalperson_gender', violation_error_message='Invalid gender.'),
        ),
        migrations.AddConstraint(
            model_name='naturalperson',
            constraint=models.CheckConstraint(condition=models.Q(('salary__gte', 0.0)), name='chk_naturalperson_salary', violation_error_message='Invalid salary.'),
        ),
    ]
